targets:
  local-staging:
    type: local
    environment: staging
    path: staging
    require_marker: true

  local-production:
    type: local
    environment: production
    path: prod
    require_marker: true
